#ifndef __BF3Classes__H_
#define __BF3Classes__H_

#include "Includes.h"
#include "FB SDK/Offsets.h"
#include "FB SDK/EASTL_Includes.h"
#include "FB SDK/Enumerations.h"
#include "FB SDK/EA.h"
#include "FB SDK/Juice.h"
#include "FB SDK/Frostbite_Classes.h"
#include "FB SDK/ClassT.h"
#include "FB SDK/Vec2.h"
#include "FB SDK/Vec3.h"
#include "FB SDK/Vec4.h"
#include "FB SDK/Mat4.h"
#include "FB SDK/LinearTransform.h"
#include "FB SDK/Quat.h"
#include "FB SDK/QuatTransform.h"
#include "FB SDK/AxisAlignedBox.h"
#include "FB SDK/Plane.h"
#include "FB SDK/Frustum.h"
#include "FB SDK/Color32.h"
#include "FB SDK/Havok.h"
#include "FB SDK/ScreenshotModule.h"
#include "FB SDK/ISocket.h"
#include "FB SDK/BitArray.h"
#include "FB SDK/MessageListener.h"
#include "FB SDK/eastl_arena_allocator.h"
#include "FB SDK/InBitStream.h"
#include "FB SDK/OutBitStream.h"
#include "FB SDK/Timer.h"
#include "FB SDK/network.h"
#include "FB SDK/online.h"
#include "FB SDK/ant.h"
#include "FB SDK/PlayerManager.h"
#include "FB SDK/ControlObjectState.h"
#include "FB SDK/MemoryArena.h"
#include "FB SDK/String.h"
#include "FB SDK/ITypedObject.h"
#include "FB SDK/DataContainer.h"
#include "FB SDK/Asset.h"
#include "FB SDK/Score.h"
#include "FB SDK/DebugRender.h"
#include "FB SDK/Pad.h"
#include "FB SDK/MotionController.h"
#include "FB SDK/Device.h"
#include "FB SDK/Keyboard.h"
#include "FB SDK/Mouse.h"
#include "FB SDK/BorderInputNode.h"
#include "FB SDK/System.h"
#include "FB SDK/PropertyModificationListener.h"
#include "FB SDK/SupportsWeakPtr.h"
#include "FB SDK/PlayerData.h"
#include "FB SDK/GameTime.h"
#include "FB SDK/WorldRenderer.h"
#include "FB SDK/Level.h"
#include "FB SDK/DataBusData.h"
#include "FB SDK/EntityBusData.h"
#include "FB SDK/EventConnection.h"
#include "FB SDK/Blueprint.h"
#include "FB SDK/DebrisManager.h"
#include "FB SDK/PhysicsEntityUserData.h"
#include "FB SDK/IPhantom.h"
#include "FB SDK/IMoving.h"
#include "FB SDK/IRotation.h"
#include "FB SDK/IPhysics.h"
#include "FB SDK/IHavok.h"
#include "FB SDK/PhysicsRenderParams.h"
#include "FB SDK/Hook.h"
#include "FB SDK/MaterialGridManager.h"
#include "FB SDK/EntityEvent.h"
#include "FB SDK/DataContext.h"
#include "FB SDK/EntityBus.h"


#include "FB SDK/MaterialGridData.h"
#include "FB SDK/MaterialContainerPair.h"
#include "FB SDK/MaterialRelationPropertyPair.h"
#include "FB SDK/MaterialInteractionGridRow.h"
#include "FB SDK/PhysicsEntityBaseRayCast.h"
#include "FB SDK/PhysicsEntityContainer.h"
#include "FB SDK/EntityGridQueryJobData.h"


#include "FB SDK/IPhysicsRayCaster.h"
#include "FB SDK/HavokPhysicsManager.h"
#include "FB SDK/WeakTokenHolder.h"
#include "FB SDK/OnlineID.h"
#include "FB SDK/Player.h"
#include "FB SDK/EntryInput.h"
#include "FB SDK/EntityCollection.h"
#include "FB SDK/SpottingComponentData.h"
#include "FB SDK/GameObjectData.h"
#include "FB SDK/TeamInfo.h"
#include "FB SDK/GameEntityData.h"
#include "FB SDK/TeamEntityData.h"
#include "FB SDK/GameRenderer.h"
#include "FB SDK/WeaponComponent.h"
#include "FB SDK/EntryComponent.h"
#include "FB SDK/CameraComponent.h"
#include "FB SDK/CacheData.h"
#include "FB SDK/PropertyWriter.h"

#include "FB SDK/Main.h"

#include "FB SDK/CharacterPhysicsEntity.h"
#include "FB SDK/RayCastHit.h"
#include "FB SDK/RayCastResult.h"
#include "FB SDK/SoldierEntity.h"
#include "FB SDK/BulletEntityData.h"

#include "FB SDK/CtrRefBase.h"
#include "FB SDK/ComponentInfo.h"
#include "FB SDK/ComponentCollection.h"
#include "FB SDK/FieldInfo.h"
#include "FB SDK/TypeInfo.h"
#include "FB SDK/TypeManager.h"
#include "FB SDK/ClassInfo.h"
#include "FB SDK/ModuleManager.h"
#include "FB SDK/KindOfEntityIterator.h"






#include "FB SDK/Mesh.h"
#include "FB SDK/Ragdoll.h"
#include "FB SDK/CameraShakeManager.h"

#include "FB SDK/Client.h"
#include "FB SDK/ClientGameContext.h"
#include "FB SDK/ClientComponent.h"
#include "FB SDK/ClientSpottingComponent.h"
#include "FB SDK/ClientSpottingTargetComponent.h"
#include "FB SDK/ClientCameraComponent.h"
#include "FB SDK/ClientPlayerView.h"
#include "FB SDK/ClientCameraContext.h"
#include "FB SDK/ClientGameEntity.h"
#include "FB SDK/ClientPlayer.h"
#include "FB SDK/ClientPhysicsEntity.h"
#include "FB SDK/ClientControllableEntity.h"
#include "FB SDK/ClientCharacterEntity.h"
#include "FB SDK/ClientAntAnimatableComponent.h"
#include "FB SDK/ClientProximityHookImpl.h"
#include "FB SDK/ClientEntryComponentSound.h"
#include "FB SDK/ClientGameWorld.h"
#include "FB SDK/ClientSoldierWeapon.h"
#include "FB SDK/ClientBoneCollisionComponent.h"
#include "FB SDK/ClientSoldierAimingSimulation.h"
#include "FB SDK/ClientEntryComponent.h"
#include "FB SDK/ClientAnimatedSoldierWeaponHandler.h"
#include "FB SDK/ClientSoldierWeaponsComponent.h"
#include "FB SDK/ClientWeapon.h"	
#include "FB SDK/ClientSoldierEntity.h"
#include "FB SDK/ClientVehicleEntity.h"
#include "FB SDK/ClientStanceFilterComponent.h"


#include "FB SDK/Entity.h"
#include "FB SDK/EntityStuff.h"

#include "FB SDK/PhysicsEntity.h"
#include "FB SDK/PhysicsEntityData.h"

#include "FB SDK/Vehicle.h"
	
#include "FB SDK/AnimatedSoldierWeapon.h"
#include "FB SDK/WeaponFiringShooter.h"
#include "FB SDK/WeaponSwayCallbackImpl.h"
#include "FB SDK/WeaponModifier.h"	
#include "FB SDK/WeaponProjectileModifier.h"	
#include "FB SDK/WeaponShotModifier.h"
#include "FB SDK/WeaponEntityData.h"
#include "FB SDK/WeaponInfo.h"
#include "FB SDK/WeaponOffsetData.h"
#include "FB SDK/WeaponSwitching.h"
#include "FB SDK/ClientSoldierReplication.h"


#include "FB SDK/Rumble.h"
#include "FB SDK/Level.h" //
#include "FB SDK/UI.h"    //
#include "FB SDK/GameTime.h"
#include "FB SDK/WorldRenderer.h"	//

#include "FB SDK/IRender.h"	//
#include "FB SDK/IStateRenderer.h"	//
#include "FB SDK/ScreenRenderer.h"	//

#include "FB SDK/Snowroller.h"
#include "FB SDK/Server.h"	//

#endif // __BF3Classes__H_
